MOVEMENT_RECEIVE = "receive"
MOVEMENT_OPENING = "opening_balance"
MOVEMENT_SALE = "sale"
MOVEMENT_ADJUSTMENT = "adjustment"
MOVEMENT_TRANSFER_IN = "transfer_in"
MOVEMENT_TRANSFER_OUT = "transfer_out"
MOVEMENT_DAMAGE = "damage"
MOVEMENT_LOSS = "loss"
MOVEMENT_RETURN = "return"
MOVEMENT_QUARANTINE = "quarantine"
MOVEMENT_RELEASE = "release"

VALID_MOVEMENT_TYPES = {
    MOVEMENT_RECEIVE,
    MOVEMENT_OPENING,
    MOVEMENT_SALE,
    MOVEMENT_ADJUSTMENT,
    MOVEMENT_TRANSFER_IN,
    MOVEMENT_TRANSFER_OUT,
    MOVEMENT_DAMAGE,
    MOVEMENT_LOSS,
    MOVEMENT_RETURN,
    MOVEMENT_QUARANTINE,
    MOVEMENT_RELEASE,
}
